### ISSUE TITLE
ksmbd and WINS

### ISSUE THREAD

**Issue by Mile-Lile** [namjaejeon/ksmbd#349]
This is question, not issue... does ksmbd has WINS nssswitch module (libwbclient), can it resolve WINS names?
If do so, what is directive?
Thx

**Comment by namjaejeon** [comment]
Hi,

No, It doesn't support. Is there strong reason that you need it?

**Comment by Mile-Lile** [comment]
Hi namjaejeon, thank you for answering. No "strong" reason but I'll try to explain it. On embedded systems wsdd2 (Netgear code similar to M$ LLMNR) is used for windows discovery service (shares, printers, scanners etc.). On Linux and MacOS it doesn't work, simply not designed for these OSes... so, there is ksmbd-avahi-service but it is bigger then ksmbd itself... So, I was thinking about WINS netbios but it seems this increases code size to much... Linux community is bigger every day, and most of new Linux users like to se their shares and computers in GNOME way and not use console etc... Sorry if I made you trouble, wasn't intentional just trying to find best solution to my situation...

**Comment by namjaejeon** [comment]
Ah, GNOME way ? I need to check what is GNOME way.

**Comment by Mile-Lile** [comment]
It is desktop environment (GUI). Like MS Windows... opposite of CLI -
console line interface

**Comment by namjaejeon** [comment]
The computer name is used instead of IP address in GNOME GUI ? nautilus is one of GNOME GUI ?

**Comment by Mile-Lile** [comment]
Microsoft proprietary name service protocols start with NetBIOS Name
Service which was based on LAN-local (non-routable) broadcasts. I say
"Microsoft proprietary", but technically it originated with IBM as part of
the Server Message Block (SMB) protocols. As SMB file service became a de
facto industry standard, many OSes had to adopt NetBIOS Name Service in
their SMB clients and servers at the very least. Later, Microsoft created
WINS to provide a server-based unicast solution for this same kind of
Microsoft-proprietary name resolution. When Apple created mDNS under the
name "Rendezvous" (later renamed Bonjour) and took it to the IETF to
eventually become IETF ZeroConf, Microsoft bewilderingly decided to do
their own slightly different, incompatible mDNS-like think that they called
"Link-Local Multicast Name Resolution" (LLMNR). In the Microsoft world,
requests for ".local" hosts usually goes to LLMNR, as if to spite
ZeroConf's standardized use of ".local". Microsoft also uses UPnP for
discovering some things on LANs, like routers (Wi-Fi APs and NAT gateways).

Linux, including Google Android, seem to be gravitating toward ZeroConf for
LAN-based serverless name resolution now. Google ported Apple's
POSIX-compliant open source "mDNSResponder" daemon to Linux for use in
Android; it's what implements Android's "Network Service Discovery" (NSD)
APIs.

Like macOS, Linux uses NetBIOS Name Service and WINS for the sake of
connecting to SMB servers.

It's a huge mess, and which protocol(s) get used for a particular thing
depends on which OS you're on, which APIs your software calls, and many
other things.
share <https://superuser.com/a/1359746>  improve this answer
<https://superuser.com/posts/1359746/edit>  follow

**Comment by Mile-Lile** [comment]
@namjaejeon 
I was asked by @Neustradamus 
to relaunch this ticket...
