### ISSUE TITLE
SMB2_TREE_CONNECT_HE fails to connect with the error -22

### ISSUE THREAD

**Issue by ahmedarif193** [namjaejeon/ksmbd#366]
Hello, 
I'm posting an issue about not being able to connect to a shared folder, the windows prompt permission denied with the following dmesg detailed output : 

ksmbd: ksmbd_conn_handler_loop:314: RFC1002 header 170 bytes
ksmbd: ksmbd_verify_smb_message:150: got SMB2 command
ksmbd: smb2_calc_size:252: SMB2 data length 50 offset 120
ksmbd: smb2_calc_size:269: SMB2 len 170
ksmbd: smb2_set_rsp_credits:377: credits: requested[1] granted[1] total_granted[107]
ksmbd: ksmbd_conn_handler_loop:314: RFC1002 header 120 bytes
ksmbd: smb2_get_ksmbd_tcon:103: skip to check tree connect request
ksmbd: ksmbd_verify_smb_message:150: got SMB2 command
ksmbd: smb2_calc_size:252: SMB2 data length 48 offset 72
ksmbd: smb2_calc_size:269: SMB2 len 120
**ksmbd: smb2_tree_connect:1717: tree connect request for tree tmp folder treename \\192.168.2.1\tmp folder
ksmbd: __process_request:153: Failed to process 3 [-22]**
ksmbd: smb2_set_rsp_credits:377: credits: requested[1] granted[1] total_granted[107]

looking in smb2pdu.h I found that the work method of the request with a given ID 3 belong to SMB2_TREE_CONNECT_HE

below the specs of the hardware and the configuration

`
softwate specs : 
OS : OPENWRT 
ksmbd-tools version : 3.3.3
cifsd version 3.3.3

Hardware specs : 
kernel ARCH : aarch64
Userspace arch : arm

cat /proc/cpuinfo :
processor       : 0
cpu model       : ARM
BogoMIPS        : 100.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer : 0x42
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0x100
CPU revision    : 0
.....

smb.conf : 

[global]
        netbios name = OpenWrt
        server string = Ksmbd on OpenWrt
        workgroup = WORKGROUP
        interfaces = BR_LAN
        bind interfaces only = yes
        ipc timeout = 20
        deadtime = 15
        map to guest = Bad User
        smb2 max read = 64K
        smb2 max write = 64K
        smb2 max trans = 64K
        cache read buffers = no
        cache trans buffers = no

[tmp folder]
        path = /tmp
        valid users = ahmed
        create mask = 0666
        directory mask = 0777
        read only = no
        guest ok = no
        inherit owner = yes
        hide dot files = no`

**Comment by namjaejeon** [comment]
Have you added "ahmed" user account using adduser(or useradd) in your system ? You can check it in /etc/passwd.

**Comment by ahmedarif193** [comment]
yes it's already there : 

grep ahmed /etc/passwd
ahmed:x:1018:1018:Linux User,,,:/home/ahmed:/bin/sh

**Comment by ahmedarif193** [comment]
There is more : 

 ksmbd.adduser -a ahmed05 -p ahmed05
[smbuseradd/2826]: INFO: Could not open converter from “UTF-8” to “UTF-16LE”
[smbuseradd/2826]: INFO: Will try 'UCS-2LE' and 'UTF-8'
[smbuseradd/2826]: INFO: User 'ahmed05' added

digging into the source code i found that the ksmbd kernel space sends the cridentials to ksmbd-tools over ipc netlink to validate the entries, which this one replies with 4 = KSMBD_TREE_CONN_INVALID_USER, the switch case in smb2_tree_connect function reply with STATUS_ACCESS_DENIED (22)

Is there any codage issue with libiconv ?

here is the linking status :
ldd ksmbd.adduser
        libc.so.6 => /lib/libc.so.6 (0xf6fc1000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xf6f96000)
        /lib/ld-linux.so.3 (0xf7110000)

**Comment by namjaejeon** [comment]
You have added this parameter in smb.conf => valid users = ahmed
Have you added "ahmed" account using ksmbd.adduser ?

can you share your user account DB info using this command ?
cat /etc/ksmbd/ksmbdpwd.db 

Thanks.
