### ISSUE TITLE
Fedora 32 server and WIN10 client use SMB direct failed

### ISSUE THREAD

**Issue by wqlxx** [namjaejeon/ksmbd#385]
hi, I build ksmbd and ksmbd-tools in Fedora 32 (kernel version is 5.6.6-300.fc32.x86_64) with mellanox cx-5 RDMA network adapter. I use windows 10 client to connect to Fedora server. But I found that RDMA did not work. I still saw network traffic in TASK MANAGER in windows 10 client. I am wondering whether smb direct is working properly.

**Comment by namjaejeon** [comment]
@MistyMoonR Windows 10 pro doesn't, but Windows 10 workstation(and enterprise) support it.
