### ISSUE TITLE
Server reset is in progress, can't start daemon

### ISSUE THREAD

**Issue by ChungkiWoo** [namjaejeon/ksmbd#386]
Hello Namjae Jeon.

How are you? :)
There is an issue with SMB in ToMobile (sharing content from flip to moble device) function in flip.
When try to connect secondly in iOS(AOS as well), connection can not be estabished.
 
it is supposed to work like 

- wifi connection -> Connect smb server -> successful connection -> ios device starts to receive packets from flip's smb server -> Receive packet successfully

but it works like below

- We check wifi connection -> Connect smb server -> Get error code: "Error Domain=NEhotspotConfiguration Code=1"

One info is...

Normal case:
sh-3.2# ps ax | grep cifsd
 3598 ?        Ss     0:00 cifsd -n
 3599 ?        Sl     0:00 cifsd -n
 3981 ?        S+     0:00 grep cifsd

Error case:
sh-3.2# ps ax | grep cifsd
 4261 ?        S+     0:00 grep cifsd

In Server side in error case, below log is printed.

    [3-2963.0879] ksmbd: handle_startup_event:371: Server reset is in progress, can't start daemon
    [3-2963.0891] send signal SIG : 15, cifsd(6354)->cifsd(6354) handler:0001539d __send_signal

Is there any idea for this issue?

Thank you.

**Comment by ChungkiWoo** [comment]
BTW, I am in charge of SMB server here these days :)

**Comment by namjaejeon** [comment]
If I re-run the cifsd daemon again in the problem situation, does it work well? It seems that flip try to re-run in a situation where the ksmbd kernel has not yet completed the reset.
And Can you update ksmbd and ksmbd.mountd(old cifsd) to the latest version ?

**Comment by namjaejeon** [comment]
> BTW, I am in charge of SMB server here these days :)

k... If there is anything I can do to help, I will. Let me know it.

**Comment by ChungkiWoo** [comment]
> > BTW, I am in charge of SMB server here these days :)
> 
> k... If there is anything I can do to help, I will. Let me know it.

Thank you very much :)

**Comment by ChungkiWoo** [comment]
If we start cifsd again after killing all cifsd with 'killall cifsd' for example, how long time do we need to wait for not meet below issue?

[3-2963.0879] ksmbd: handle_startup_event:371: Server reset is in progress, can't start daemon

I think it is some kind of timing issue..

**Comment by mmakassikis** [comment]
Have you tried running "ksmbd.control -s" to kill established connections ?

**Comment by namjaejeon** [comment]
Hm.. Probably need to check stats of ksmbd server. 

1. check /sys/class/ksmbd-control/stats
- Flip can check sysfs file for ksmbd if ksmbd server is still resetting ksmbd threads.
#cat /sys/class/ksmbd-control/stats
 2 reset 445 0
- check if "reset" is changed to "startup"
#cat /sys/class/ksmbd-control/stats
 2 startup 445 0

Two ways.
1. your application can directly check stats.
2. ksmbd.control -s option check stats.

You can add this check code to ksmbd.control and reset ksmbd server using ksmbd.control -s option.
I prefer that that stats in this sysfs file is checked by ksmbd.control(control.c) in ksmbd-tools.

So, The script will be the following.
ksmbd.control -s  <=== kill cifsd(ksmbd.mountd) and reset server.
ksmbd.mountd   <=== restart

**Comment by namjaejeon** [comment]
@mmakassikis Thanks for your comment. Right. need to use ksmbd.control to reset or shutdown server.

**Comment by namjaejeon** [comment]
@ChungkiWoo Any news ? Let me know if you have fixed your issue.
