### ISSUE TITLE
Protocol freedom website

### ISSUE THREAD

**Issue by charsi** [namjaejeon/ksmbd#387]
https://github.com/namjaejeon/ksmbd/blob/6ddb3cffdc68762e85a39b669f9712ed6e14ecd5/README.md?plain=1#L24

Looks like the protocol freedom domain  has been taken over by a generic tech bog. Is there a better link to them the readme could point to instead ?  
https://protocolfreedom.org/ <-- doesn't have any info about protocol freedom anymore. Cached versions in search engines also show the tech blog content so the change can't be too recent.

**Comment by namjaejeon** [comment]
I don't know why protocolfreedom site die. Why are you looking for it?

**Comment by charsi** [comment]
I was just trying to learn more about them.
