### ISSUE TITLE
Extreme Load Averages

### ISSUE THREAD

**Issue by FireCulex** [namjaejeon/ksmbd#388]
Decided to give this a go as samba4-libs didn't fit on my device.

After copying under 75mb total but 200 files from ubuntu, router would either reboot or display "IPC daemon response for 20s" . I had to reboot. probably. logread -f and monitoring top doesn't reveal anything. I did not have issues with playback or reading, but I primarily focused on being able to write.

```
[ 2116.732689] do_page_fault(): sending SIGSEGV to pool for invalid read access from 00424000
[ 2116.741059] epc = 77e9b850 in libc.so[77e24000+9c000]
[ 2116.746164] ra  = 0040772b in ksmbd.mountd[400000+12000]
[ 2117.772422] ksmbd: handle_startup_event:372: Reconnect to a new user space daemon
[ 2118.761145] Unable to close RPC pipe 2

• Copying a 3gb ubuntu iso from windows recieved a load average upwards of 80
• Deleting a directory with a lot of small files, ~200 items.
```

```
Load average: 184.87 57.69 20.27 3/340 4352
• Copying another 100mb file
• router rebooted
```

```
Mem: 100564K used, 22636K free, 268K shrd, 4668K buff, 60888K cached
CPU:   0% usr  99% sys   0% nic   0% idle   0% io   0% irq   0% sirq
Load average: 13.20 7.74 3.69 8/100 4417
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
 4118     2 root     RW       0   0%  14% [ksmbd:8336]
 4176     2 root     RW       0   0%  14% [ksmbd:8340]
 4116     2 root     RW       0   0%  14% [ksmbd:8335]
 4188     2 root     RW       0   0%  14% [ksmbd:8345]
 4321     2 root     RW       0   0%  14% [ksmbd:8352]
 4395     2 root     RW       0   0%  14% [ksmbd:8356]
 4184     2 root     RW       0   0%  14% [ksmbd:8344]

• fresh reboot sometimes gets stuck, requiring reboot again 
• no one able to access any shares
```

For comparison if I transfer the same file via vsftpd the load stays at about 1~6.

I didn't want to go back to 19.07. I figured out how to extroot with a 512mb usb. Samba4-libs turns out to be 60mb by itself. Everything installed was under 200mb. My router only has 16mb...

With Samba4 the load was under 7. Copying 300 tiny files as before, flawless, load avg 2. No reboots.

OpenWRT 21.02 WNDR3800

**Comment by mmakassikis** [comment]
What ksmbd version is that ? Can you try with latest code (+updated ksmbd-tools), possibly lowering "smb2 max credit" ?
This should help have a manageable load.

On the other hand, your first log shows ksmbd.mountd crashed, so it would be interesting to know why that happened. Is it reproducible ? What client are you using to connect to the share ?

**Comment by FireCulex** [comment]
It appears to be 3.3.9. I tried to drop in 3.4.3 but anything above 3.4.0 bottoms out with:
`make[4]: *** No rule to make target '/home/culex/OpenWRT/owrt2102/build_dir/target-mips_24kc_musl/linux-ath79_generic/ksmbd-3.4.3/ksmbd_spnego_negtokeninit.asn1.c', needed by '/home/culex/OpenWRT/owrt2102/build_dir/target-mips_24kc_musl/linux-ath79_generic/ksmbd-3.4.3/ksmbd_spnego_negtokeninit.asn1.o'.  Stop.`

do_page_faults()  is common with the windows client. copy some files, delete some files, it'll will usually happen when I'm not looking. intermittent. ubuntu has a very high chance of nuking the router requiring a rebuild. occasionally the windows client will too, just not every time.

```
Sun Jan  2 10:22:14 2022 kern.err kernel: [23333.663161] ksmbd: __ipc_heartbeat:835: No IPC daemon response for 21s
Sun Jan  2 10:22:16 2022 kern.err kernel: [23336.358163] ksmbd: ksmbd_conn_handler_loop:335: sock_read failed: -143

• deleted or copy hundreds of files.  windows client
• IPC also happens if transfering a large file on the windows client, drop to 0 bytes transfer, and top shows 100% io
• samba io is usually only 0-3%
```

I'll try to figure out how to solve the build issue.

**Comment by mmakassikis** [comment]
ksmbd_spnego_negtokeninit.asn1.c should be a generated file. When building in tree, ksmbd selects ASN1=y in the kernel config.
What does the Makefile look like ?
Looking at this [source](https://github.com/openwrt/packages/blob/master/kernel/ksmbd/Makefile), you may need to add kmod-asn1-decoder to the list of dependencies.

The transfer stuck at 99% on Windows was an issue in ksmbd.mountd which has been fixed, so you shouldn't have that on the latest code.

**Comment by FireCulex** [comment]
I forgot to check the trunk for a newer version, thanks!  kmod-nf-nathelper-extra has the kmod-asn1-decoder as a dependency.

Ksmbd/Kmod Version 3.4.3
I did come across the do_page_fault once, requires ksmbd to be stopped and started again.  the IPC warnings are gone.

Copying a large file will drop to 0 bytes,  100% io. It might restart itself, or it might reboot which is more likely.  Ubuntu is still the fastest way to bring it down.
```
Mem: 96928K used, 26264K free, 240K shrd, 5812K buff, 32864K cached
CPU:   0% usr  99% sys   0% nic   0% idle   0% io   0% irq   0% sirq
Load average: 128.88 85.45 57.21 2/225 11971
  PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
11949     2 root     RW       0   0%  99% [ksmbd:12274]
```

Niether of these had any effect.
```
smb2 max credits = 128 

--- a/smb2pdu.h
#define SMB2_MAX_CREDITS		128
```

It's an ext4 file system with lvm2 mdadm raid 5 with 3 networked drives.

**Comment by mmakassikis** [comment]
> Ksmbd/Kmod Version 3.4.3

The code that handles the "smb2 max credits" was committed after 3.4.3, so it's normal that you don't see a difference. Please test with latest code from master branch (both ksmbd and ksmbd-tools).

**Comment by FireCulex** [comment]
ksmbd.adduser is blank where it should say "New password:" 

```
$ sudo ksmbd.adduser -u culex
<blank> (enter)
New Password: cool (enter)
Retype new password: 
[ksmbd.adduser/16566]: ERROR: Passwords don't match

```

Confirmed using git-src master for ksmbd-tools and ksmbd.

Copying a 3gb file, few minutes stalls to 0 bytes, 100% io, 100+ load avg. Managed to cancel before it rebooted. No messages.

upon restarting the service
```
Mon Jan  3 20:23:18 2022 authpriv.notice sudo:    culex : TTY=pts/4 ; PWD=/home/culex ; USER=root ; COMMAND=/etc/init.d/ksmbd restart
Mon Jan  3 20:23:18 2022 daemon.notice ksmbd: Stopping Ksmbd userspace service.
Mon Jan  3 20:23:18 2022 daemon.err rmmod: unloading the module failed
Mon Jan  3 20:23:18 2022 daemon.info ksmbd: triggering kill_server
Mon Jan  3 20:23:18 2022 kern.info kernel: [43941.918765] ksmbd: kill command received
Mon Jan  3 20:23:21 2022 daemon.notice ksmbd: Starting Ksmbd userspace service.
Mon Jan  3 20:23:24 2022 kern.err kernel: [43948.143365] ksmbd: Total credits overflow: 1
```
credits overflow is always 1 regardless of setting. If i set `smb2 max credits = 1` I get  Unknown error 524 so clearly it does something.

**Comment by mmakassikis** [comment]
ksmbd.mountd need to be rebuilt so that "smb2 max credits" option can be used: you don't need to reconfigure users.

> Copying a 3gb file, few minutes stalls to 0 bytes, 100% io, 100+ load avg.

When you say 'stalls to 0 bytes', is that a message on the client ? Which client are you using ?
Can you see the file being written on the share ?

**Comment by FireCulex** [comment]
```
culex@Culex-VM:~/OpenWRT/git-src/ksmbd$ git log
commit 510c8e900b0d6a4b45c1e7e05521310521afe8fb (HEAD -> master, origin/master, origin/HEAD)
Author: Namjae Jeon <linkinjeon@kernel.org>
Date:   Fri Dec 31 09:23:53 2021 +0900

    ksmbd: limits exceeding the maximum allowable outstanding requests
    
...

culex@Culex-VM:~/OpenWRT/git-src/ksmbd-tools$ git log
commit 957e2c22b360727c01f138070418a9e01196a8b1 (HEAD -> master, origin/master, origin/HEAD)
Author: Namjae Jeon <linkinjeon@kernel.org>
Date:   Wed Dec 29 14:54:11 2021 +0900

    ksmbd-tools: add support for smb2 max credits parameter
    
...
```

```
culex@OpenWrt:/etc/ksmbd$ cat smb.conf
[global]
        netbios name = |NAME|
        server string = |DESCRIPTION|
        workgroup = |WORKGROUP|
        interfaces = |INTERFACES|
        bind interfaces only = yes
        ipc timeout = 20
        deadtime = 15
        map to guest = Bad User
        smb2 max read = 64K
        smb2 max write = 64K
        smb2 max trans = 64K
        cache read buffers = no
        cache trans buffers = no
        smb2 max credits = 128
```

![ShareX_xjsMl24Dev](https://user-images.githubusercontent.com/9983630/148353742-d7264eae-1297-42f1-a2c0-80cd2512d45b.png)
![explorer_OJQtSvfF1q](https://user-images.githubusercontent.com/9983630/148357203-239dc292-71fb-43ee-896b-72b78b172631.png)
![firefox_grNqjdc1k9](https://user-images.githubusercontent.com/9983630/148357220-c3c64f83-f754-467d-a104-8a0f0562cd11.png)
![firefox_9VNNQ7b2SW](https://user-images.githubusercontent.com/9983630/148357819-a5ff10ad-9ac0-4f55-8079-5f8a14df95aa.png)
![firefox_kSErtyTAUv](https://user-images.githubusercontent.com/9983630/148357712-2fdb923f-3a12-4119-ae8d-b0e606a0dc46.png)
![firefox_fIhUqrhpa6](https://user-images.githubusercontent.com/9983630/148365298-34e3596f-4b57-4062-88af-5817e7d3a8b4.png)


00:33 I canceled at 3% when it said 0 bytes. Next time at 00:45 I let it run till it rebooted.

The filename gets written, it shows 3gb, but it's obviously corrupted. If i do a mass copy with ubuntu I believe I've seen a lot of filenames with 0 bytes. 100% io Windows will say Speed: 0 bytes.  It might continue, it might not,  it usually doesn't, it will be 0% io and 100% sys. Always 100+ load. Technically Samba4 is working without requiring any parameters...

**Comment by namjaejeon** [comment]
> smb2 max credits = 128

Are you setting too small a value? Does the problem occur even when set to default(8192) or 1024 value ?

**Comment by FireCulex** [comment]
128, 1024, 8192 - excessive load, excessive wait, speed 0, then reboot.  no difference unless i set it to like 1, then I cant connect.

It just dawned on me that wait is actually io in top.

samba4 comparison
![firefox_BeBwO26NmD](https://user-images.githubusercontent.com/9983630/148376787-a5ddecb8-994c-4cfa-af69-fd17b1ff5ea9.png)
![firefox_BQZBPyDIJq](https://user-images.githubusercontent.com/9983630/148377020-9c9c69ff-f02e-4959-898e-51942a5a6d2f.png)
![firefox_3TjVVTTZBW](https://user-images.githubusercontent.com/9983630/148377029-3e256ec8-8eac-4484-aeaf-bdedc3c85a61.png)

**Comment by namjaejeon** [comment]
Could you please give us tcpdump(or wireshark dump)  to analyse packets ?

**Comment by FireCulex** [comment]
Can you narrow your request?

![Wireshark_4qLvMOdVVK](https://user-images.githubusercontent.com/9983630/148380113-f4b76d42-3ba0-41ac-a7af-c35ba853bd86.png)


![Wireshark_6p54ks75Wh](https://user-images.githubusercontent.com/9983630/148379963-c6f56c08-10f4-42e5-b806-aa85c8579e13.png)

Is that what your looking for?

**Comment by mmakassikis** [comment]
For what it's worth, the 'cache read buffers/cache trans buffers' options don't do anything.

Are you using the same smb2 max read/write parameters when testing with samba ?

The increased wait means some work is taking a long time to complete (which would be IO here). Since this takes a while, other work is accumulated in a queue, i.e: the system is loaded with more work. Hence the increased load average.

You mentioned you have a RAID array of networked drives. Can you test with a share backed by a local drive ?

**Comment by FireCulex** [comment]
> You can capture packets using wireshark on problem situation. and send dump file to me. (my email : [linkinjeon@kernel.org](mailto:linkinjeon@kernel.org))

Scrubbing was my main concern, windows is super leaky. But did you want gigs of tracing?? Let me know if what I sent wasn't enough and want the whole transfer.

>Are you using the same smb2 max read/write parameters when testing with samba ?

No. Samba is out of the box. Requires nothing to work.

>You mentioned you have a RAID array of networked drives. Can you test with a share backed by a local drive ?

I got a 16gb usb stick.  Ran the test 3x. No 100% io. No Speed 0 bytes. No Reboot.  Unfortunately it does appear to be a factor.

43% sirq which I guess isn't mdadm, 20% io. 70-100 load average is still present.

Ubuntu however will still kill it rather quickly. No change there.

**Comment by mmakassikis** [comment]
> No. Samba is out of the box. Requires nothing to work.

Have you tested ksmbd with the default "smb2 max read/write/trans" values ?

> Ubuntu however will still kill it rather quickly. No change there.

Is that with the USB stick or the RAID ?

**Comment by FireCulex** [comment]
>Is that with the USB stick or the RAID ?

USB.

> Have you tested ksmbd with the default "smb2 max read/write/trans" values ?

Since they were provided by the distro I had not touched them.  Nailed it.

Removing max read/write/trans/credits, copying to the RAID, load avg 13, no crashes. If 100% io it will recover quickly, doesn't cause the router to be unresponsive and reboot. CrystalDiskMark consistently shows 11.2% improvement over samba4.
Ubuntu copying 300 small files, no crashes now either. Everything is perfect.

Distro defaults appears to have been responsible.
After extensive testing I believe this issue is resolved. Thanks!

**Comment by namjaejeon** [comment]
> Scrubbing was my main concern, windows is super leaky. But did you want gigs of tracing?? Let me know if what I sent wasn't enough and want the whole transfer.

I need the whole packet dump file. We shouldn't close this issue as it is. Your problem happen when setting 64K to "smb2 max read/write/trans" values. Right ?
```
        smb2 max read = 64K
        smb2 max write = 64K
        smb2 max trans = 64K
```
