### ISSUE TITLE
ksmbd logging and ECONNREFUSED from smb client

### ISSUE THREAD

**Issue by leeyh8901** [namjaejeon/ksmbd#389]
Hello Namjae Jeon.

How are you? :)
There is an issue with SMB in ToMobile (sharing content from flip to moble device) function in flip.
When try to connect from mobile device, it received ECONNREFUSED error, connection can not be estabished.

Unusually, the results different depending on the type of interface, in p2p0, has problem but eth0 has no problem for samba connection.  (ping is ok both interface)

Is there any idea about this issue?

In additionally, is there a way to leave a ksmbd log to file or tmpfs? 
I want to get history of ksmbd like client connection information. 

if exist, please share how to get log. 

Thanks :)

**Comment by namjaejeon** [comment]
Hello,

> Unusually, the results different depending on the type of interface, in p2p0, has problem but eth0 has no problem for samba connection. (ping is ok both interface)

Have you checked packets using tcpdump ? There should be SMB packets in dump.

Let me know more information.
 1. Please show your smb.conf to us (file location seems to be in /etc/ksmbd/ or /etc/cifsd/ )
 2. ifconfig -a
 3. if possible, please give us tcpdump.

> In additionally, is there a way to leave a ksmbd log to file or tmpfs?

There is no such function in ksmbd. It should be a kernel feature, not ksmbd...

**Comment by leeyh8901** [comment]
Hello, 

I'll share result of "netstat -an" . In problem case, there is no LISTEN socket on 445 port. 

[normal case]
sh-3.2# netstat -an | grep 445
tcp6       0      0 :::445                  :::*                    LISTEN     
tcp6       0      0 :::445                  :::*                    LISTEN

[problem case] 
sh-3.2# netstat -an | grep 445
... 

above both case using same smb.conf. 

Is there any idea about this issue?
I wonder where should I check. 

Thanks. 



In additionally, I attach smb.conf. 

[global]
    netbios name = CIFSD
    ipc timeout = 1
    guest account = GUEST
    map to guest = bad user
    bind interfaces only = yes
    interfaces = p2p0 lo
    server max protocol = SMB2
[homes]
    comment = content server share
    path = /mnt/samba
    writeable = no
    oplocks = no
    max connections = 10
    guest ok = yes
[IPC$]
    available = no
    writeable = yes
    browseable = no

**Comment by namjaejeon** [comment]
@leeyh8901 There is no ifconfig -a result and tcpdump file. Without that, it can be difficult to figure out what the problem is.
If you hard to share dump file to me, Please try to do two thing.
 1. check if there are smb or smb2 packets on tcpdump using wireshark. If there is no smb packets, It means that smb requests are not arrived to ksmbd server.
 2. check if you can connection ksmbd server using ToMobile after removing the following two parameters in smb.conf.
```
bind interfaces only = yes
interfaces = p2p0 lo
```

**Comment by leeyh8901** [comment]
Thanks you for answer. 

1. check if there are smb or smb2 packets on tcpdump using wireshark. If there is no smb packets, It means that smb requests are not arrived to ksmbd server.
no, there is no smb or smb2 packet. I think no one LISTENING 445 port, so client couldn't connect to 445 port. 

2. check if you can connection ksmbd server using ToMobile after removing the following two parameters in smb.conf.
In case of using eth0, smbd works well. So it seems there is something difference in p2p0 interface. 

I think cifsd or ksmbd should open and LISTEN 445 port to service. 

In what situation does the following listen port not occur? 
Or where is the part that creates the listen port?

sh-3.2# netstat -an | grep 445
tcp6 0 0 :::445 :::* LISTEN
tcp6 0 0 :::445 :::* LISTEN

Thanks

**Comment by namjaejeon** [comment]
Isn't the 445 port below open?
```
tcp6 0 0 :::445 :::* LISTEN
tcp6 0 0 :::445 :::* LISTEN
```

**Comment by leeyh8901** [comment]
Yes, in problem case, no 445 port is opened.

**Comment by namjaejeon** [comment]
okay, Can you check if ksmbd kernel threads are also running using "ps -ax | grep ksmbd" ?

**Comment by leeyh8901** [comment]
there is no ksmbd process. 

sh-3.2# ps -ax | grep ksmbd
 5353 ?        S+     0:00 grep ksmbd

**Comment by namjaejeon** [comment]
Can you debug ksmbd_netdev_event() function ? create_socket() is not called or create_socket() seems to return error.

**Comment by namjaejeon** [comment]
Is this an occasional issue? or Does it happen 100%?

**Comment by leeyh8901** [comment]
> Can you debug ksmbd_netdev_event() function ? create_socket() is not called or create_socket() seems to return error.

ok, I'll check the error log about that functions. 
It happen 100%

**Comment by namjaejeon** [comment]
Let me know if there is any update.

**Comment by namjaejeon** [comment]
@leeyh8901 ping?

**Comment by leeyh8901** [comment]
I'm sorry for late answer. And I found the root cause why no ksmbd daemon. 
I found that the cifsd module was not loaded normally, and after fix the problem, ksmbd worked well.
