### ISSUE TITLE
add support for dkms

### ISSUE THREAD

**Issue by cathaysia** [namjaejeon/ksmbd#393]
I am using Fedora, and it's kernel update is very frequent, so if there has not  suppport of dkms, I must rebuild kernel module every when I update my kernel, and it's troublesome for me.

I had give a try for make a dkms, however, I failed. Can someone give me a hand? Or just add support in this repo?

**Comment by namjaejeon** [comment]
ksmbd in Archlinux seems to support it. Can you check https://aur.archlinux.org/cgit/aur.git/tree/dkms.conf?h=ksmbd-dkms ? and contribute it to ksmbd if it work fine.

**Comment by cathaysia** [comment]
close by https://github.com/namjaejeon/ksmbd/commit/ac62bc68219e63e23f4e0fcb60a8a8ff3c5ba5b4
