### ISSUE TITLE
macos client empty share (invisible)

### ISSUE THREAD

**Issue by cyayon** [namjaejeon/ksmbd#398]
Hello,

I am trying to mount some ksmbd share on a macos (12.3.1) client, and encounter a very strange issue.

Some directories on root of the share are invisible. I thank that it was a permission issue, but it is not...
With a windows client and the same share, i have no issue.

I tried to tweak some params on /etc/nsmb.conf (on macos) to force SMB2, SMB3, etc... no way, always the same issue.

I have no particular kernel log message on ksmbd server. Only these messages on ksmbd service startup :
ksmbd: Failed to bind socket: -98
ksmbd: Failed to shutdown socket: -107

I am running the very last kernel 5.17.1, but i had the same issue with my previous kernel 5.16.4.

Any suggestions ?

thanks

**Comment by namjaejeon** [comment]
Is there any way to reproduce this issue without Macbook ?

**Comment by cyayon** [comment]
Hi,

you can close the ticket.
I have managed to resolve the issue, I think it was a mistake from myself.
Sorry for the delay.

**Comment by namjaejeon** [comment]
Okay, Thanks!
