### ISSUE TITLE
Network Shares show no files after 22.03.2 update

### ISSUE THREAD

**Issue by alex-manutd** [namjaejeon/ksmbd#413]
Had to reinstall the ksmbd packages after updating the firmware and maybe I didn't do something right.  My shares are visible, the drives show a size of 9.75MB each and my files are not visible.  I plugged the drives into my linux box and the files are fine.   Has anyone had this?

**Comment by namjaejeon** [comment]
What is 22.03.2 ? ubuntu version ?

>  the drives show a size of 9.75MB each and my files are not visible.

How do you check it ? Let me know how to reproduce it on my side.

**Comment by neheb** [comment]
22.03.2 is a version of OpenWrt. ksmbd and ksmbd-tools are at version 3.4.5

**Comment by alex-manutd** [comment]
Fixed by installing Kmod-fs-ext4.

**Comment by namjaejeon** [comment]
@alex-manutd Okay, If you find the solution, Please close this.
