### ISSUE TITLE
VFS module with ksmbd

### ISSUE THREAD

**Issue by tienthanh411** [namjaejeon/ksmbd#415]
I am trying to enable the VFS module to store ACLs in the extended attribute `security.NTACL`, but so far no luck. These are the settings that I have tried:
```
[global]
  ...
  vfs objects = acl_xattr
  ea support = yes
  writeable = yes
  security = user
  acl_xattr:ignore system acls = yes
  acl_xattr:default acl style = windows
 ...

[share]
  read only = no
  path = /home/user/sambashare
```
I could set the `security.NTACL` manually with `setfacl`, meaning that it is enabled in my file system. But for whatever reason, I can't set it through SMB. I have tried `smbclient`. Also, tried mount the SMB share on a Windows machine and set the ACLs through Windows settings. The ACLs are always stored in `system.posix_acl_access` and `user.DOSATTRIB`. I am using Linux kernel 5.15.30 in a Ubuntu 22.04 machine. 

Could anybody please help me with this?

**Comment by namjaejeon** [comment]
@tienthanh411 Hi!, okay. I am wondering you can store security.NTACL on samba ?

**Comment by tienthanh411** [comment]
@namjaejeon I am not sure what you meant. ksmbd doesn't support VFS? The source code seems to suggest it does.

**Comment by namjaejeon** [comment]
@tienthanh411 There is no error log from ksmbd in dmesg ?

**Comment by namjaejeon** [comment]
@tienthanh411 

> tried mount the SMB share on a Windows machine and set the ACLs through Windows settings.

Could you please add the following change and can see the print after set ACLs through windows ?
```
diff --git a/vfs.c b/vfs.c
index 3c0e605..9442ffa 100644
--- a/vfs.c
+++ b/vfs.c
@@ -1580,6 +1580,8 @@ int ksmbd_vfs_set_sd_xattr(struct ksmbd_conn *conn,
                                sd_ndr.offset, 0);
        if (rc < 0)
                pr_err("Failed to store XATTR ntacl :%d\n", rc);
+       else
+               pr_err("succeed to store XATTR ntacl\n");
 
        kfree(sd_ndr.data);
 out:
```

**Comment by tienthanh411** [comment]
Samba smbd works fine with VFS on my machine. I am using the exact same configuration in both smbd and ksmbd, only changed the share location path. Attached is the ksmbd logs when I mounted the share on a Windows machine and created a file named "abc.txt". Also the smb configuration file. 

[ksmbd_logs.txt](https://github.com/namjaejeon/ksmbd/files/10359912/ksmbd_logs.txt)
[smb.conf.txt](https://github.com/namjaejeon/ksmbd/files/10359919/smb.conf.txt)

**Comment by namjaejeon** [comment]
You don't need to turn debug mode on. I shared the patch to check if ksmbd_vfs_set_sd_xattr() is called.

**Comment by namjaejeon** [comment]
Have you applied the patch I provided to you ?

**Comment by tienthanh411** [comment]
No, I didn't. That would involve building a custom kernel, right? There was already some debug logs about xattr and windows acl in the file I attached.

**Comment by namjaejeon** [comment]
man ksmbd.conf

```
       vfs objects (S)
              List of the VFS modules to overload I/O operations with.  Available VFS modules are
              acl_xattr and streams_xattr.

              Default: vfs objects =
```
vfs objects is parameter for share section. Can you try to move it to each share section from global ?

**Comment by namjaejeon** [comment]
(S) means share section.

**Comment by tienthanh411** [comment]
Thanks, moving vfs objects to the share section works!

**Comment by tienthanh411** [comment]
Yeah it was a simple modification. I think these kinds of configuration differences to samba could be highlighted somewhere. Otherwise, people who are not so familiar to SMB like me wouldn't notice :)
