### ISSUE TITLE
A ksmbd_work without SMB2_FLAGS_ASYNC_COMMAND needs call "cancel_fn" in "smb2_cancel"?

### ISSUE THREAD

**Issue by lihua-theone** [namjaejeon/ksmbd#419]
In "smb2_cancel" function, at file "smb2pdu.c", lines 6798-6799 have called "cancel_fn" for hdr->Flags with SMB2_FLAGS_ASYNC_COMMAND, at line 6819 has not call the "cancel_fn". If hdr->Flags without SMB2_FLAGS_ASYNC_COMMAND, needs call "cancel_fn" also?

**Comment by namjaejeon** [comment]
Yes, It is not needed. Because ->cancel_fn is set in setup_async_work(). Can you tell me why you ask it ?

**Comment by lihua-theone** [comment]
@namjaejeon oh, sorry. Just I read some commits modified codes while git pull, observed that block call  "cancel_fn" for all conditions. No  other special ideas.
