### ISSUE TITLE
Windows client takes a long time to run .exe/.msi

### ISSUE THREAD

**Issue by bacon-cheeseburger** [namjaejeon/ksmbd#420]
Using kernel 6.2.0 with Debian Testing here for ksmbd. Server min and max protocol is set to SMB3_11. Gigabit wired network. Client is Windows 10. For some reason when I run an exe/msi (for example, the LibreOffice installer, 337MB) on the share (+x is set), it takes forever (2min45sec in my test) before I'm even prompted if I'm sure I want to run the `unverified` file. If I click the installer and immediately restart ksmbd, I get prompted immediately. If I let the installer sit while it decompresses, it takes forever. If it starts decompressing and I restart ksmbd, it goes fast like I'd expect.

I copied a 5GB to the share at 110MB/sec, but copying the file back from the share varied between 30MB/sec-68MB/sec. I tested both directions with iperf3 and got full bandwidth.

Not sure what is causing it to choke in this way. This problem only started somewhat recently but I'm not sure which kernel version it started at. Any ideas?

**Comment by namjaejeon** [comment]
Okay. encryption may be enable ? Can you try it with "smb3  encryption  =  disabled in smb.conf" ?
Let me know your ksmbd-tools version. Please try it with the latest source of master branch.

**Comment by bacon-cheeseburger** [comment]
"smb3 encryption" was set to "no" but I changed it to "disabled" and restarted. Unfortunately it didn't help. I've got ksmbd-tools 3.4.7-1 (amd64), which looks the same as current master. Any other ideas?

**Comment by namjaejeon** [comment]
Please dump packets using wireshark. I need to find a hint from that.

**Comment by bacon-cheeseburger** [comment]
I'm not experiencing this problem anymore with current stable kernel version 6.4.11 and not sure which exact kernel version the problem was resolved. I think it's safe to close this ticket.

**Comment by bacon-cheeseburger** [comment]
I'm not experiencing this problem anymore with current stable kernel version 6.4.11 and not sure which exact kernel version the problem was resolved. I think it's safe to close this ticket.
