### ISSUE TITLE
The oplock feature will cause right-click attributes to freeze.

### ISSUE THREAD

**Issue by Cong827** [namjaejeon/ksmbd#428]
The configuration is as follows：
server max protocol = SMB2_02
oplocks = yes
sm2 leases = no

When I use windows to access the folder, right-clicking to view the file properties will cause a freeze.

Analyzing the source code, the wait_event_time_out function exits after timeout（35 * HZ） every time. Before this, the server will not respond to the oplock acknowledge message.

**Comment by Cong827** [comment]
This issue dont not exist on ksmbd.

**Comment by namjaejeon** [comment]
Ah, You are saying that your problem is fixed ?

**Comment by Cong827** [comment]
Hi,
I&nbsp;solved&nbsp;this&nbsp;problem.
This&nbsp;problem&nbsp;does&nbsp;not&nbsp;exist&nbsp;on&nbsp;ksmbd.&nbsp;I&nbsp;introduced&nbsp;this&nbsp;issue&nbsp;during&nbsp;the&nbsp;process&nbsp;of&nbsp;modifying&nbsp;the&nbsp;ksmbd&nbsp;code.I&nbsp;am&nbsp;trying&nbsp;to&nbsp;implement&nbsp;a&nbsp;similar&nbsp;io_uring&nbsp;technology&nbsp;for&nbsp;ksmbd.The&nbsp;focus&nbsp;is&nbsp;to&nbsp;separate&nbsp;message&nbsp;processing&nbsp;from&nbsp;IO&nbsp;processing,&nbsp;ensuring&nbsp;that&nbsp;both&nbsp;can&nbsp;achieve&nbsp;maximum&nbsp;throughput.The&nbsp;introduction&nbsp;of&nbsp;this&nbsp;logic&nbsp;has&nbsp;affected&nbsp;the&nbsp;processing&nbsp;of&nbsp;some&nbsp;SMB&nbsp;messages,&nbsp;thereby&nbsp;introducing&nbsp;this&nbsp;issue.
Best&nbsp;Regards!


---Original---
From: &quot;Namjae ***@***.***&gt;
Date: Tue, Aug 29, 2023 11:41 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;&quot;State ***@***.***&gt;;
Subject: Re: [namjaejeon/ksmbd] The oplock feature will cause right-clickattributes to freeze. (Issue #428)




 
Ah, You are saying that your problem is fixed ?
 
&mdash;

**Comment by namjaejeon** [comment]
@Cong827 ?

**Comment by Cong827** [comment]
I solved this problem.
This problem does not exist on ksmbd. I introduced this issue during the process of modifying the ksmbd code.I am trying to implement a similar io_uring technology for ksmbd.The focus is to separate message processing from IO processing, ensuring that both can achieve maximum throughput.The introduction of this logic has affected the processing of some SMB messages, thereby introducing this issue.

**Comment by namjaejeon** [comment]
> I am trying to implement a similar io_uring technology for ksmbd.

Oh! Sound great! Is there any plan to contribute this feature after implementation is complete ?

**Comment by namjaejeon** [comment]
I wonder current status of io_uring for ksmbd, If possible, It would be great if you can introduce it on linux kernel SMB mailing list and samba tech list.

**Comment by Cong827** [comment]
Yes, currently in the testing phase, as I am not clear about the implementation details of the SMB protocol. My current demo does not introduce io_uring API. Instead, two queues have been implemented for ksmbd, one for message processing and the other for IO processing. At the appropriate time in the future, I will contribute to the realization.

**Comment by namjaejeon** [comment]
This is big news for me and ksmbd developers:)
I recommend that you introduce this work and current status and simple test results on mailing list(linux-cifs@vger.kernel.org).
samba developer is also trying to apply io_uring to samba and he is sharing it's status on conference.(https://www.youtube.com/watch?v=K5wIJaIVrug).

Thanks!

**Comment by namjaejeon** [comment]
> I am trying to implement a similar io_uring technology for ksmbd.

Can I ask about this ? I missed "similar" word :). I thought it is io_uring(). Is there any reason why you doesn't apply io_uring and trying implement similar one ?

**Comment by Cong827** [comment]
> > I am trying to implement a similar io_uring technology for ksmbd.
> 
> Can I ask about this ? I missed "similar" word :). I thought it is io_uring(). Is there any reason why you doesn't apply io_uring and trying implement similar one ?

Based on my current understanding of ksmbd, the cost of adding io_uring feature support to it is enormous. Therefore, I plan to implement a demo to verify the optimization effect.I personally believe that introducing the x feature is of great help in improving ksmbd IO throughput. Ksmbd can achieve maximum network throughput and IO throughput. Before that, I was trying some low-cost validation work.

**Comment by Cong827** [comment]
> > I am trying to implement a similar io_uring technology for ksmbd.
> 
> Can I ask about this ? I missed "similar" word :). I thought it is io_uring(). Is there any reason why you doesn't apply io_uring and trying implement similar one ?

Based on my current understanding of ksmbd, the cost of adding io_uring feature support to it is enormous. Therefore, I plan to implement a demo to verify the optimization effect.I personally believe that introducing the io_uring feature is of great help in improving ksmbd IO throughput. Ksmbd can achieve maximum network throughput and IO throughput. Before that, I was trying some low-cost validation work.

**Comment by namjaejeon** [comment]
@Cong827 Okay. Let me know if you are ready to open it. Thanks for your work!

**Comment by namjaejeon** [comment]
@Cong827 Hi, Could you please share current status to me ? Because I am very interested in this work!

**Comment by Cong827** [comment]
I'm sorry for taking the time to reply to you. My personal work has recently changed, and the implementation of related technologies may take some time. In my opinion, io_uring does not improve the performance of ksmbd. If ksmbd wants to further improve performance, it needs to reduce the work overhead caused by the hand_loop function through shared memory and more efficient lock-free queues. Currently, the processing of each packet relies on work_queue, which will bring enough process switching overhead, and the performance is not ideal in scenarios where there are enough control packets. Just replacing ksmbd's read, write and other calls with io_uring will improve performance to a certain extent. But asynchronous IO doesn't exactly play a bigger role. In a large file transfer scenario, the file size exceeds the available memory. The writing speed of files is limited by the IO speed, which will be reflected in the device busy or congestion control strategy of Block IO. My current work is not to implement io_uring for ksmbd, but to reduce the process switching overhead for ksmbd. Of course, I found this very difficult, especially when oplock and other related messages exist.

**Comment by namjaejeon** [comment]
> My current work is not to implement io_uring for ksmbd, but to reduce the process switching overhead for ksmbd. Of course, I found this very difficult, especially when oplock and other related messages exist.

Okay. I completely agree with your analysis. I hope the current implementation goes well. If you have difficulty implementing it, please share the problem so we can work on it together.
