### ISSUE TITLE
Session not destroy correctly?

### ISSUE THREAD

**Issue by MiaoLiHua** [namjaejeon/ksmbd#432]
@namjaejeon 
I connect to ksmbd by ubuntu as client. And sometimes, when the client setup the session, it only step to "ntlm_negotiate" and then no anything follow packets. Of course, the connection not related with the session's ksmbd_chann_list by a channel. 

Consequently, while the connection closed, in function "ksmbd_sessions_deregister", directly return at line 227 because not removed the associated channel in function "ksmbd_chann_del". So, the session not be destroyed. 

By the way, function "ksmbd_sessions_deregister" why not only loop conn->sessions even for the conn's binding is true, for destroy a session, already check it's ksmbd_chann_list is empty or not. Similar as:

	void ksmbd_sessions_deregister(struct ksmbd_conn *conn) {
		struct ksmbd_session *sess;
		unsigned long id;
		xa_for_each(&conn->sessions, id, sess) {
			ksmbd_chann_del(conn, sess);
			if (xa_empty(&sess->ksmbd_chann_list)) {
				xa_erase(&conn->sessions, sess->id);
				ksmbd_session_destroy(sess);
			}
		}
	}

**Comment by namjaejeon** [comment]
> And sometimes, when the client setup the session, it only step to "ntlm_negotiate" and then no anything follow packets.

Hm... ksmbd response session setup and ubuntu client doesn't send second session setup request(authentication) ?

**Comment by MiaoLiHua** [comment]
In file user_session.c, line 227.
Yes, some times ubuntu client doesn't send second session setup request. That cause the session in the conn's sessions, but the session's ksmbd_chann_list is empty.

**Comment by namjaejeon** [comment]
understood. I will fix it. Thanks for your report!

**Comment by namjaejeon** [comment]
Can you test this patch ? (https://github.com/namjaejeon/ksmbd/commit/d9a454e86538e16994b2b90c6d21ea580d86fe17)

**Comment by namjaejeon** [comment]
@MiaoLiHua Ping?

**Comment by MiaoLiHua** [comment]
I tested the patch, and it can work while only one ubuntu client connected to the ksmbd and the client broken the subsequent session setup request. But, I read you code, the 'break' cause only check the first session in 'conn->sessions'?
If the same client setup two uncompleted sessions, the codes would delete only first one? Similar, in loop 'hash_for_each(sessions_table, bkt, sess, hlist)'.

	xa_for_each(&conn->sessions, id, sess) {
		ksmbd_chann_del(conn, sess);
		break;  //ONLY deal with the first session in conn->sessions?
	}

I still suggest loop conn->sessions, as long as ‘sess->ksmbd_chann_list’ is empty, directly destroy the session.



	void ksmbd_sessions_deregister(struct ksmbd_conn *conn) {
		struct ksmbd_session *sess;
		unsigned long id;
		xa_for_each(&conn->sessions, id, sess) {
			ksmbd_chann_del(conn, sess);
			if (xa_empty(&sess->ksmbd_chann_list)) {
				xa_erase(&conn->sessions, sess->id);
				/* ksmbd_session_destroy will remove session from sessions_table */
				ksmbd_session_destroy(sess); 
			}
		}
	}

**Comment by namjaejeon** [comment]
There is some issue in the patch. I will update it.

**Comment by MiaoLiHua** [comment]
> There is some issue in the patch. I will update it.

Or, add the ref_count to the struct session, back to normal c++ method?

**Comment by namjaejeon** [comment]
@MiaoLiHua Can you review  ksmbd_sessions_deregister() function on #master ?

https://github.com/namjaejeon/ksmbd/blob/fd7303380c67186ca870482a04e082d9322a7511/mgmt/user_session.c#L217

Thanks.

**Comment by MiaoLiHua** [comment]
I checked all, and not found any problem. That is great work!

**Comment by MiaoLiHua** [comment]
@namjaejeon 
But I have a question, in the function "ksmbd_expire_session", loop all sessions in sessions_table and if a session expired, remove it from "sessions_table" and destroy it. How about the destroying session's "ksmbd_chann_list"? Needs call ksmbd_chann_del every channel in the list?

**Comment by namjaejeon** [comment]
@MiaoLiHua ksmbd_session_destroy() call free_channel_list function that delete channels in ksmbd_chann_list.

**Comment by namjaejeon** [comment]
Okay. Closed this issue.
