### ISSUE TITLE
RDMA Doesn't Work When Windows Client Connected

### ISSUE THREAD

**Issue by a13547** [namjaejeon/ksmbd#435]
Server: RHEL 9 with kernel-lt (6.1) in elrepo, Connectx-3 Pro NIC, Debian 11 with 6.x kernel
Client: Windows 11 Pro Workstation, Windows Server 2019

First I tried to set up an nvme-of controller in server side and an initiator in client side, proofed that RDMA connections between them worked. Then I set up a share with ksmbd, using the ksmbd.conf.example file, but RDMA doesn't work. Get-smbmultichannelconnection shows the ksmbd server isn't RDMA capable. 

I try to disable smb compression, limit protocol to smb3, unplug all other NICs, but nothing works. Debug of RDMA also shows nothing. 

Is there any tricks, prerequisites, or settings?

**Comment by namjaejeon** [comment]
Have you addded "server multi channel support = yes" parameter in [global] section of your ksmbd.conf ?

**Comment by a13547** [comment]
> Have you addded "server multi channel support = yes" parameter in [global] section of your ksmbd.conf ?

Yes, but still didn’t work. 
I googled and found https://forum.level1techs.com/t/how-can-i-help-with-the-new-truenas-100g-testing/179052/30?page=2 said their Win-Linux RDMA connection doesn’t work either.

**Comment by a13547** [comment]
> Have you ever tested large file copy test ? Windows switches to RDMA when writing large files.

Yes, I haven't noticed RDMA traffic in performance monitor when transferring ~80GB files. But I see dmesg printed "Unsupported RPC MsFteWds", "Unsupported RPC mdssvc" and "Unable to open RPC pipe -22". Does that indicate some RDMA configure error in Windows or in the server?

**Comment by namjaejeon** [comment]
> But I see dmesg printed "Unsupported RPC MsFteWds", "Unsupported RPC mdssvc" and "Unable to open RPC pipe -22". Does that indicate some RDMA configure error in Windows or in the server?

No, It is not related to RDMA. Can you send me the packet dump(wireshark or tcpdump) when connecting ksmbd server through windows client ?

**Comment by a13547** [comment]
Here is the dump file using Wireshark. It's strange that Get-SmbConnection shows the connection uses 3.1.1 while Wireshark indicates SMB2. Thank you! 

[dump.zip](https://github.com/namjaejeon/ksmbd/files/11730197/dump.zip)

**Comment by namjaejeon** [comment]
Ah. You have dumped packet while accessing files. I want to check packets when connecting ksmbd server. i.e. Please dump when you open network drive and login with your id.

**Comment by a13547** [comment]
[dump.zip](https://github.com/namjaejeon/ksmbd/files/11730764/dump.zip)

Thank for your patience!

**Comment by namjaejeon** [comment]
When I checked your dump, Your NIC doesn't support RDMA in ksmbd.

Can you debug why rdma_capable is false in ksmbd_rdma_capable_netdev() ?

**Comment by a13547** [comment]
> When I checked your dump, Your NIC doesn't support RDMA in ksmbd.
> 
> Can you debug why rdma_capable is false in ksmbd_rdma_capable_netdev() ?

It didn’t work even if I directly change  rdma_capable=true. 😂 
Now giving up. 
Anyway, thanks a lot!

**Comment by a13547** [comment]
@namjaejeon I finally figured out where the problem is. 
The Makefile seems not to enable SMB Direct support by default in making standalone module or the whole kernel.
I followed the instructions to copy ksmbd sources to 5.10.179 kernel tree in Debian, found in menuconfig that "Support for SMB Direct protocol" is not selected by default. I selected it manually, compile the whole kernel, and it works!
I don't have any knowledge about Makefile, so could you please check it out and make some modifications?
Thank you!

**Comment by a13547** [comment]
I manage to build standalone module with RDMA enabled by manually adding "#define CONFIG_SMB_SERVER_SMBDIRECT" to the header file. That's so exciting! And thank you again!
