### ISSUE TITLE
Access times bad after update to kernel 6.7.x

### ISSUE THREAD

**Issue by bacon-cheeseburger** [namjaejeon/ksmbd#470]
Hi,
I recently upgrading my stable kernel from 6.5.13 to 6.7.1. The ksmbd server is running on Debian Linux, and my main client accessing it is Windows 10. Everything was nice & fast with 6.5.13, however after upgrading the kernel, access has slow considerably.

1. Directory access
There's a long delay, like when a mechanical harddrive is sleeping and has to spin-up first (even though the shares are SSD), when I access directories for the first time now.

2. Moving files with drag & drop, deleting files
If I drag & drop a file into a subdir for example, the copy/move process takes a long time, 30+ seconds. If I delete a file, that also takes a very long time, 40 seconds to delete a 2MB in my test.

EDIT: I tested stable kernel 6.7.0 as well and the same problem exists so it seems 6.7.x is affected, not just 6.7.1.

**Comment by namjaejeon** [comment]
1. Directory access
2. Moving files with drag & drop, deleting files

This is fixed with https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/fs/smb/server?h=v6.8-rc1&id=77bebd186442a7d703b796784db7495129cc3e70

This patch will be applied to 6.7.2 or 6.7.3 soon.

**Comment by namjaejeon** [comment]
If you want to fix it on your kernel, please temporarily apply this patch.

**Comment by bacon-cheeseburger** [comment]
I applied the patch to 6.7.1 to test and it resolved the problem. Thank you for letting me know the status - glad someone else caught it already and was fixed. :)

**Comment by namjaejeon** [comment]
Thanks for your report and confirmation:) I made a mistake when implementing new feature(v2 leases).
