### ISSUE TITLE
router oom on write even with cache trans buffers = no

### ISSUE THREAD

**Issue by romanovj** [namjaejeon/ksmbd#496]
ksmbd.conf
```
[global]
        netbios name = router
        server string = Ksmbd on OpenWrt
        workgroup = WORKGROUP
        interfaces =
        bind interfaces only = yes
        ipc timeout = 20
        deadtime = 15
        map to guest = Bad User
        smb2 max read = 64K
        smb2 max write = 64K
        smb2 max trans = 64K
        cache read buffers = no
        cache trans buffers = no

######### Dynamic written config options #########

[usb]
        path = /mnt/sdb
        force user = root
        force group = root
        create mask = 0666
        directory mask = 0777
        read only = no
        guest ok = yes
```
ksmbd: next 6a50a6c0b123ed8bb6c5c9d19d434de5226cbf39
ksmbt-tools: 3.5.3
kernel: 5.15.167
device: openwrt router, arm64 with 256MB RAM

No problems only when mounting cifs with `-o rw,cache=none` vs default `cache=strict`.

**Comment by namjaejeon** [comment]
> No problems only when mounting cifs with -o rw,cache=none vs default cache=strict.

What is meaning ? oom problem is related to cifs.ko mount option ?

**Comment by namjaejeon** [comment]
Can you share oom backtrace log with me ?

**Comment by namjaejeon** [comment]
If you change cache trans buffers = yes, oom does not happen ?

**Comment by namjaejeon** [comment]
> router oom on write with cache trans buffers = no

This is subject of this ISSUE. So I thought cache trans buffers parameter was related to OOM.
You told me "No changes". What is meaning ?

**Comment by namjaejeon** [comment]
Can you try to change smb2 max credits parameter in your ksmbd.conf ?

[global]
smb2 max credits = 1024

**Comment by namjaejeon** [comment]
Please close this issue if your issue is clear.

**Comment by namjaejeon** [comment]
Yes. Thanks for your report:)
